# Site settings
title: TimRayburn.net
email: tim@timrayburn.net
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://timrayburn.net"
twitter_username: trayburn
github_username:  trayburn

# Build settings
markdown: kramdown
permalink: pretty
gems:
- jekyll-compass
